In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('C://Users//atul/Desktop/Coaching/data/Data_Train.xlsx')
data.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
data['Date_of_Journey'] = pd.to_datetime(data['Date_of_Journey'],format='%d/%m/%Y')
data.Date_of_Journey

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
5       2019-06-24
6       2019-03-12
7       2019-03-01
8       2019-03-12
9       2019-05-27
10      2019-06-01
11      2019-04-18
12      2019-06-24
13      2019-05-09
14      2019-04-24
15      2019-03-03
16      2019-04-15
17      2019-06-12
18      2019-06-12
19      2019-05-27
20      2019-03-06
21      2019-03-21
22      2019-04-03
23      2019-05-01
24      2019-05-06
25      2019-06-09
26      2019-06-01
27      2019-05-15
28      2019-06-18
29      2019-06-15
           ...
10653   2019-05-01
10654   2019-06-12
10655   2019-05-03
10656   2019-04-06
10657   2019-05-06
10658   2019-06-18
10659   2019-05-01
10660   2019-03-21
10661   2019-05-09
10662   2019-03-24
10663   2019-06-06
10664   2019-04-09
10665   2019-04-27
10666   2019-06-12
10667   2019-03-12
10668   2019-05-09
10669   2019-06-15
10670   2019-05-12
10671   2019-06-06
10672   2019-06-27
10673   2019-05-27
10674   2019-03-12
10675   2019-06-09
10676   2019-05-01
10677   2019-05-21
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10683, dtype: datetime64[ns]

In [9]:
date_of_journey = pd.DataFrame(data['Date_of_Journey'].dt.dayofweek)
date_of_journey

       Date_of_Journey
0                    6
1                    2
2                    6
3                    6
4                    4
5                    0
6                    1
7                    4
8                    1
9                    0
10                   5
11                   3
12                   0
13                   3
14                   2
15                   6
16                   0
17                   2
18                   2
19                   0
20                   2
21                   3
22                   2
23                   2
24                   0
25                   6
26                   5
27                   2
28                   1
29                   5
...                ...
10653                2
10654                2
10655                4
10656                5
10657                0
10658                1
10659                2
10660                3
10661                3
10662                6
10663                3
10664                1
10665                5
10666                2
10667                1
10668                3
10669                5
10670                6
10671                3
10672                3
10673                0
10674                1
10675                6
10676                2
10677                1
10678                1
10679                5
10680                5
10681                4
10682                3

[10683 rows x 1 columns]

In [10]:
data["Date_of_Journey"]=date_of_journey

In [11]:
data

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,6,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,2,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,6,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,6,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,4,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
5,SpiceJet,0,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
6,Jet Airways,1,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087
7,Jet Airways,4,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270
8,Jet Airways,1,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087
9,Multiple carriers,0,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625
10,Air India,5,Delhi,Cochin,DEL → BLR → COK,09:45,23:00,13h 15m,1 stop,No info,8907
11,IndiGo,3,Kolkata,Banglore,CCU → BLR,20:20,22:55,2h 35m,non-stop,No info,4174
12,Air India,0,Chennai,Kolkata,MAA → CCU,11:40,13:55,2h 15m,non-stop,No info,4667
13,Jet Airways,3,Kolkata,Banglore,CCU → BOM → BLR,21:10,09:20 10 May,12h 10m,1 stop,In-flight meal not included,9663
14,IndiGo,2,Kolkata,Banglore,CCU → BLR,17:15,19:50,2h 35m,non-stop,No info,4804
15,Air India,6,Delhi,Cochin,DEL → AMD → BOM → COK,16:40,19:15 04 Mar,26h 35m,2 stops,No info,14011
16,SpiceJet,0,Delhi,Cochin,DEL → PNQ → COK,08:45,13:15,4h 30m,1 stop,No info,5830
17,Jet Airways,2,Delhi,Cochin,DEL → BOM → COK,14:00,12:35 13 Jun,22h 35m,1 stop,In-flight meal not included,10262
18,Air India,2,Delhi,Cochin,DEL → CCU → BOM → COK,20:15,19:15 13 Jun,23h,2 stops,No info,13381
19,Jet Airways,0,Delhi,Cochin,DEL → BOM → COK,16:00,12:35 28 May,20h 35m,1 stop,In-flight meal not included,12898
20,GoAir,2,Delhi,Cochin,DEL → BOM → COK,14:10,19:20,5h 10m,1 stop,No info,19495
21,Air India,3,Banglore,New Delhi,BLR → COK → DEL,22:00,13:20 19 Mar,15h 20m,1 stop,No info,6955
22,IndiGo,2,Banglore,Delhi,BLR → DEL,04:00,06:50,2h 50m,non-stop,No info,3943
23,IndiGo,2,Banglore,Delhi,BLR → DEL,18:55,21:50,2h 55m,non-stop,No info,4823
24,Jet Airways,0,Kolkata,Banglore,CCU → BOM → BLR,18:55,08:15 07 May,13h 20m,1 stop,In-flight meal not included,7757
25,Jet Airways,6,Delhi,Cochin,DEL → IDR → BOM → COK,21:25,12:35 10 Jun,15h 10m,2 stops,No info,13292
26,IndiGo,5,Delhi,Cochin,DEL → LKO → COK,21:50,03:35 02 Jun,5h 45m,1 stop,No info,8238
27,GoAir,2,Delhi,Cochin,DEL → BOM → COK,07:00,12:55,5h 55m,1 stop,No info,7682
28,Vistara,1,Banglore,Delhi,BLR → DEL,09:45,12:35,2h 50m,non-stop,No info,4668
29,Vistara,5,Chennai,Kolkata,MAA → CCU,07:05,09:20,2h 15m,non-stop,No info,3687
...,...,...,...,...,...,...,...,...,...,...,...
10653,Jet Airways,2,Kolkata,Banglore,CCU → BOM → BLR,14:05,12:00 02 May,21h 55m,1 stop,No info,14388
10654,SpiceJet,2,Banglore,Delhi,BLR → DEL,05:55,08:35,2h 40m,non-stop,No check-in baggage included,4319
10655,Jet Airways,4,Mumbai,Hyderabad,BOM → HYD,02:55,04:20,1h 25m,non-stop,No info,5678
10656,Vistara,5,Banglore,Delhi,BLR → DEL,07:00,09:40,2h 40m,non-stop,No info,5613
10657,Jet Airways,0,Kolkata,Banglore,CCU → BOM → BLR,20:00,09:20 07 May,13h 20m,1 stop,In-flight meal not included,9663
10658,Jet Airways,1,Banglore,Delhi,BLR → DEL,11:10,14:05,2h 55m,non-stop,In-flight meal not included,5769
10659,Vistara,2,Banglore,Delhi,BLR → DEL,21:00,23:50,2h 50m,non-stop,No info,4668
10660,Vistara,3,Banglore,New Delhi,BLR → DEL,21:10,00:05 19 Mar,2h 55m,non-stop,No info,4878
10661,Air India,3,Delhi,Cochin,DEL → BOM → COK,13:00,19:15,6h 15m,1 stop,No info,8372
10662,Air India,6,Kolkata,Banglore,CCU → BOM → GOI → BLR,09:25,05:35 25 Mar,20h 10m,2 stops,No info,12352
10663,Jet Airways,3,Delhi,Cochin,DEL → JAI → BOM → COK,19:30,12:35 07 Jun,17h 5m,2 stops,In-flight meal not included,11733
10664,IndiGo,1,Banglore,Delhi,BLR → DEL,18:55,21:50,2h 55m,non-stop,No info,4823
10665,IndiGo,5,Kolkata,Banglore,CCU → BLR,15:15,17:45,2h 30m,non-stop,No info,4804
10666,Jet Airways,2,Delhi,Cochin,DEL → BOM → COK,18:15,19:00 13 Jun,24h 45m,1 stop,In-flight meal not included,10262
10667,Jet Airways,1,Banglore,New Delhi,BLR → BOM → DEL,22:55,20:20 13 Mar,21h 25m,1 stop,In-flight meal not included,11087
10668,Jet Airways,3,Delhi,Cochin,DEL → JDH → BOM → COK,11:40,19:00,7h 20m,2 stops,No info,21219
10669,Air India,5,Delhi,Cochin,DEL → BOM → COK,08:00,19:15,11h 15m,1 stop,No info,9929
10670,Air India,6,Kolkata,Banglore,CCU → IXR → DEL → BLR,05:50,23:15,17h 25m,2 stops,No info,11411
10671,Air India,3,Mumbai,Hyderabad,BOM → HYD,21:05,22:25,1h 20m,non-stop,No info,3100
10672,Jet Airways,3,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
10673,Jet Airways,0,Delhi,Cochin,DEL → AMD → BOM → COK,13:25,04:25 28 May,15h,2 stops,No info,16704
10674,Jet Airways,1,Banglore,New Delhi,BLR → BOM → DEL,20:35,21:20 13 Mar,24h 45m,1 stop,In-flight meal not included,11087
10675,Air India,6,Mumbai,Hyderabad,BOM → HYD,06:20,07:40,1h 20m,non-stop,No info,3100
10676,Multiple carriers,2,Delhi,Cochin,DEL → BOM → COK,10:20,19:00,8h 40m,1 stop,No info,9794
10677,SpiceJet,1,Banglore,Delhi,BLR → DEL,05:55,08:35,2h 40m,non-stop,No check-in baggage included,3257
10678,Air Asia,1,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,5,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,5,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,4,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,3,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753